# Generated by Django 4.2.5 on 2023-09-15 21:38

import blog.models
import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Category Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.PathRename('images/blog/Categories'), verbose_name='Category Image')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True, verbose_name='Slug')),
                ('parent_slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True, verbose_name='Parent Category Slug')),
                ('active', models.BooleanField(choices=[(True, 'Publish'), (False, 'Draft')], default=False, verbose_name='Status')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Tag Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.PathRename('images/blog/Tags'), verbose_name='Category Image')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True, verbose_name='Slug')),
                ('parent_slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, null=True, unique=True, verbose_name='Parent Category Slug')),
                ('active', models.BooleanField(choices=[(True, 'Publish'), (False, 'Draft')], default=False, verbose_name='Status')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.tag', verbose_name='Parent Category')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=250, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=blog.models.PathRename('images/blog/posts/'))),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('active', models.BooleanField(choices=[(True, 'Publish'), (False, 'Draft')], default=False, verbose_name='Status')),
                ('rating', models.CharField(choices=[('excellent', 1), ('average', 0), ('bad', -1)], default='average', max_length=50)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_author', to=settings.AUTH_USER_MODEL)),
                ('category', models.ManyToManyField(blank=True, to='blog.category')),
                ('favourites', models.ManyToManyField(blank=True, default=None, related_name='favourite', to=settings.AUTH_USER_MODEL)),
                ('tag', models.ManyToManyField(blank=True, to='blog.tag')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
    ]
