# Generated by Django 4.2.5 on 2023-09-16 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='rating',
            field=models.CharField(choices=[('excellent', 1), ('average', 0), ('bad', -1)], default='average', max_length=50),
        ),
    ]
